[package]
name = "plants-n-pests"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "client"
path = "client/main.rs"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.9.1", features = ["dynamic"] }